project:
  type: website
  output-dir: docs
website:
  title: "DataExplorer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/NimaSarajpoor
      - icon: linkedin
        href: https://www.linkedin.com/in/nimasarajpoor1991/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



